export const AGENT_DISCLOSURE_COLLAPSE_EVENT = 'agent-disclosure-collapse'
export const AGENT_DISCLOSURE_COLLAPSE_MS = 360
export const AGENT_DISCLOSURE_CLOSE_DELAY_MS = 240
export const AGENT_PLAYBACK_RELEASE_MS = AGENT_DISCLOSURE_CLOSE_DELAY_MS + AGENT_DISCLOSURE_COLLAPSE_MS
