// PLAYWRIGHT_MODULE_PATH points to an existing Playwright install; no Electron/PTY processes are started.
const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')
const { pathToFileURL } = require('node:url')

async function main() {
  const root = path.resolve(__dirname, '../..')
  const outputRoot = path.join(root, '.tmp/workbench')
  fs.mkdirSync(outputRoot, { recursive: true })
  const output = fs.mkdtempSync(path.join(outputRoot, 'run-'))
  const mock = path.join(root, 'tests/browser/workbench-panels.tsx')
  await require('esbuild').build({
    entryPoints: [path.join(root, 'tests/browser/workbench.tsx')], outfile: path.join(output, 'ui.js'), bundle: true, platform: 'browser', jsx: 'automatic', tsconfig: path.join(root, 'tsconfig.json'), define: { 'process.env.NODE_ENV': '"production"' },
    plugins: [{ name: 'workbench-fixture', setup(build) {
      build.onResolve({ filter: /^@store$/ }, () => ({ path: path.join(root, 'tests/browser/workbench-store.ts') }))
      build.onResolve({ filter: /settings\/userProfile$|^@renderer\/settings$|^@services\/updaterService$|\/(emotion\/panelSettings|services\/electronAPI|services\/systemPrivilegeService)$/ }, () => ({ path: path.join(root, 'tests/browser/workbench-preferences.ts') }))
      build.onResolve({ filter: /\/(Editor|Sidebar|ChatPanel|ShellStudio|TerminalPanel|DebugPanel|EmotionAmbientGlow)$/ }, args => ({ path: path.basename(args.path), namespace: 'fixture-panel' }))
      build.onLoad({ filter: /.*/, namespace: 'fixture-panel' }, args => ({ contents: `export { ${args.path} as default, ${args.path} } from ${JSON.stringify(mock)}`, resolveDir: root }))
    } }],
  })
  const tailwind = (await import(pathToFileURL(path.join(root, 'tailwind.config.js')).href)).default
  const css = await require('postcss')([require('tailwindcss')({ ...tailwind, content: [path.join(root, 'tests/browser/workbench*.tsx'), path.join(root, 'src/renderer/components/layout/*.tsx'), path.join(root, 'src/renderer/components/common/DecorativeAnimationScope.tsx')] })]).process('@tailwind base;@tailwind components;@tailwind utilities;', { from: undefined })
  fs.writeFileSync(path.join(output, 'fixture.css'), css.css)
  fs.writeFileSync(path.join(output, 'index.html'), '<!doctype html><meta charset="utf-8"><link rel="stylesheet" href="fixture.css"><link rel="stylesheet" href="ui.css"><div id="root"></div><script src="ui.js"></script>')
  const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright')
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 920 } })
    const errors = []; page.on('pageerror', error => { errors.push(error.message); console.error('Browser error:', error.message) })
    await page.goto(pathToFileURL(path.join(output, 'index.html')).href)
    const panel = id => page.locator(`[data-dock-panel=${id}]`)
    await page.getByRole('textbox', { name: 'Agent draft' }).fill('布局切换后保留草稿')
    await page.getByRole('textbox', { name: 'Editor buffer' }).fill('const unsaved = "preserve editor"')
    const editor = await page.getByRole('textbox', { name: 'Editor buffer' }).elementHandle()
    const agent = await page.getByRole('textbox', { name: 'Agent draft' }).elementHandle()
    const set = (method, value) => page.evaluate(([method, value]) => window.dockTestStore.getState()[method](value), [method, value])
    const menu = () => page.getByRole('button', { name: '外观与布局', exact: true }).click()
    await menu()
    await page.screenshot({ path: path.join(output, 'appearance-panel.png') })
    await page.getByRole('tab', { name: '工作台', exact: true }).click()
    await page.screenshot({ path: path.join(output, 'workbench-panel.png') })
    for (const name of ['Agent 主导', '经典开发']) {
      await page.getByRole('button', { name, exact: true }).click()
      assert(await editor.evaluate(node => node.isConnected))
      assert.equal(await page.getByRole('textbox', { name: 'Agent draft' }).inputValue(), '布局切换后保留草稿')
    }
    await page.getByRole('button', { name: '编辑器下方', exact: true }).click()
    await menu()
    await page.getByRole('textbox', { name: 'Terminal buffer' }).fill('running process · terminal history')
    const terminal = await page.getByRole('textbox', { name: 'Terminal buffer' }).elementHandle()
    const scroll = page.locator('[data-fixture-scroll]')
    await scroll.evaluate(node => { node.scrollTop = 380 })
    const initial = await panel('sidebar').boundingBox()
    await menu()
    await page.getByRole('button', { name: '专注Agent', exact: true }).click()
    assert((await panel('agent').boundingBox()).width > 1300)
    await page.getByRole('button', { name: '恢复布局', exact: true }).click()
    assert.equal(await scroll.evaluate(node => node.scrollTop), 380)
    await page.getByRole('button', { name: 'Agent', exact: true }).click()
    await menu()
    await set('setChatVisible', true)
    assert(await agent.evaluate(node => node.isConnected))
    assert.equal(await page.getByRole('textbox', { name: 'Agent draft' }).inputValue(), '布局切换后保留草稿')
    // Pointer resize paints a preview only; commit happens on release.
    const divider = page.getByRole('separator', { name: '调整面板宽度' }).first()
    const handle = await divider.boundingBox()
    await page.mouse.move(handle.x + 2, handle.y + 100); await page.mouse.down(); await page.mouse.move(handle.x + 72, handle.y + 100)
    assert.equal(Math.round((await panel('sidebar').boundingBox()).width), Math.round(initial.width))
    await page.mouse.up()
    assert((await panel('sidebar').boundingBox()).width > initial.width + 50)
    await menu()
    await page.getByRole('button', { name: '将Agent左移', exact: true }).click()
    assert((await panel('agent').boundingBox()).x < (await panel('editor').boundingBox()).x)
    await page.getByRole('button', { name: '将资源右移', exact: true }).click()
    await menu()
    assert.equal(await page.locator('.dock-panel-heading').count(), 0)
    assert.equal(await page.locator('select').count(), 0)
    for (const position of ['agent', 'bottom', 'editor']) {
      await set('setTerminalPosition', position)
      assert(await terminal.evaluate(node => node.isConnected))
      assert.equal(await page.getByRole('textbox', { name: 'Terminal buffer' }).inputValue(), 'running process · terminal history')
    }
    await set('setActiveSidePanel', 'shell')
    await page.getByRole('textbox', { name: 'Shell session' }).fill('keep shell session')
    await set('setActiveSidePanel', 'explorer')
    assert(await editor.evaluate(node => node.isConnected))
    assert.equal(await page.getByRole('textbox', { name: 'Editor buffer' }).inputValue(), 'const unsaved = "preserve editor"')
    await set('applyLayoutPreset', 'agent')
    await page.reload()
    await page.getByRole('textbox', { name: 'Agent draft' }).waitFor()
    assert.equal(await page.evaluate(() => window.dockTestStore.getState().workbenchLayout.preset), 'agent')
    await set('setTerminalPosition', 'editor')
    for (const preset of ['classic', 'agent']) {
      await set('applyLayoutPreset', preset)
      await page.screenshot({ path: path.join(output, `${preset}-light.png`) })
    }
    await page.getByRole('button', { name: '切换主题', exact: true }).click()
    await set('applyLayoutPreset', 'classic')
    await page.screenshot({ path: path.join(output, 'classic-dark.png') })
    for (const width of [960, 736]) {
      await page.setViewportSize({ width, height: 900 })
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
      await page.screenshot({ path: path.join(output, `narrow-${width}.png`) })
    }
    await page.getByRole('button', { name: 'EN / 中', exact: true }).click()
    await page.getByRole('button', { name: 'Appearance and layout', exact: true }).click()
    await page.getByRole('tab', { name: 'Workbench', exact: true }).click()
    await page.getByRole('button', { name: 'Agent first', exact: true }).click()
    assert.deepEqual(errors, [])
    console.log(`PASS: button reordering, resize preview, header-free content, presets, focus, collapse, terminal locations, shell continuity, persistence, themes and narrow windows. Artifacts: ${output}`)
  } finally { await browser.close() }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
